# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionone', models.IntegerField(max_length=100)),
                ('sessiontwo', models.IntegerField(max_length=100)),
                ('sessionthree', models.IntegerField(max_length=100)),
                ('sessionfour', models.IntegerField(max_length=100)),
                ('sessionfive', models.IntegerField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegistrationModel')),
            ],
        ),
    ]
