# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-12 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindsparkadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='notification',
            new_name='notifications',
        ),
    ]
